# This is a basic workflow to help you get started with Actions

name: lab 7 workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name : make gradle executble
        run: chmod +x .gradlew
      - name: Build with Gradle
        run: ./gradlew build
